### ISSUE TITLE
Browser Support

### ISSUE THREAD

**Issue by MacklinEngineering** [suborbital/se2-node#21]
Add browser support for the Node client library

**Comment by flaki** [comment]
Axios, the underlying request library is [isomorphic](https://axios-http.com/docs/intro), which makes it work in the browser out-of-the-box. Based on my experiments, the library will work in node.js and the browser out of the box, other non-browser non-node.js environments (such as Deno or Cloudflare Workers) will need to be tested separately.

**Comment by flaki** [comment]
As evidenced by [the demo admin UI](https://se2-stg-demo.fly.dev/admin) mini-app, this is already the case, the JS SDK supports the browser out-of-the-box, and we shall endeavor keeping it this way with future updates.
